### ISSUE TITLE
[feature request]: Design a logo

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/EazyLoader#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

The project has a logo, but it needs to be changed.

### Problem/Motivation.

N/A

### Possible Solution/Pitch.

Design a logo that is relevant to what the project is all about

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adsingh14** [comment]
Working on it.

**Comment by adsingh14** [comment]
I need some help before making changes. Do I need to install all dependencies or just replace the logo files and commit ?
