### ISSUE TITLE
[feature request]: Create YouTube Playlist Downloader

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/EazyLoader#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

I have completed YouTube Video Downloader. The Playlist Downloader is partially completed. Feel free to complete that.

### Problem/Motivation.

We often face problems in downloading the complete youtube playlist. 

### Possible Solution/Pitch.

Python zipfile module might come handy if we wish to zip all the videos into one folder.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nayan2306** [comment]
Can I do This please give me opportunity to work on this issue

**Comment by ashutoshkrris** [comment]
Alright @nayan2306 
Go ahead!
Also, I have some codes written for YouTube PLaylist Downloader that can be found in core/routes.py file.
