### ISSUE TITLE
Add animation to navbar links and buttons[feature request]:

### ISSUE THREAD

**Issue by anshika361** [ashutoshkrris/EazyLoader#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

Animation to navbar links(Home,features ,YT downloader,contact) and to buttons

### Problem/Motivation.

To give a nice appearance.

### Possible Solution/Pitch.

This feature is important as it will attract site visitors and give it a nice look.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anshika361** [comment]
> Would you like to work on it? @anshika361

No

**Comment by ashutoshkrris** [comment]
@hvb24 Ayny update?
If you're not able to do it, @tamojeetK is willing to do it
