### ISSUE TITLE
[feature request]: Create FAQ Section 

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/EazyLoader#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

Create an FAQ section on the Homepage.

### Problem/Motivation.

It would help users learn how to use the app. Users may have common questions and FAQ can be helpful for them.

### Possible Solution/Pitch.

Since the frontend is using Bootstrap, I suggest using [Bootstrap Accordion](https://getbootstrap.com/docs/5.1/components/accordion/) for the section.
Also, add a Navbar menu that links to this section.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutoshkrris** [comment]
Any update? @JaswanthReddyPadala

**Comment by JaswanthReddyPadala** [comment]
Yeah, I'll raise PR by today evening. ASAP
