### ISSUE TITLE
[bug]: Missing Meta Tags

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/EazyLoader#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Currently, there are almost no meta tags in each of the HTML files

### Expected Behavior

Each page should have its own Meta Tags that describe the page better. It would improve the SEO as well.

### To Reproduce

* Go to [metatags.io](https://metatags.io)
* Enter the URL: https://eazyloader.herokuapp.com/
* See the missing Meta Tags

### Anything else?

This is a frontend issue and is beginner-friendly.

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutoshkrris** [comment]
@tamoghna-dey 
The HTML files have almost no meta tags in them. Whenever we share the site anywhere, description and images are missing.
Need to add them

**Comment by tamoghna-dey** [comment]
Okay, may I work on this issue ?
