### ISSUE TITLE
[feature request]: YouTube Playlist Duration Calculator

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/EazyLoader#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

Create a YouTube Playlist Duration Calculator that can calculate the total duration of all videos within a playlist. Additonally, it can also show durations if we play the videos at different speeds.

### Problem/Motivation.

Well, this idea struck my mind when I saw a Youtube playlist consisting of 199 videos. We often tend to calculate total time to complete all the videos.

### Possible Solution/Pitch.

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daksh10110** [comment]
Hey, can you assign me to this issue, I would like to do it.

**Comment by daksh10110** [comment]
@ashutoshkrris I need some help with the PR, I am unable to pass some tests over there, can you please tell what to do now?
