### ISSUE TITLE
[Bug]: Heroku request timeout after 30 secs

### ISSUE THREAD

**Issue by ashutoshkrris** [ashutoshkrris/EazyLoader#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Whenever you try downloading a large video from YouTube, or user stories with many items, Heroku request timeout occurs.

According to Heroku:
> The countdown for this 30-second timeout begins after the entire request (all request headers and, if applicable, the request body) has been sent from the router to the dyno. The request must then be processed in the dyno by your application, and response delivered back to the router, within 30 seconds to avoid the timeout.

### Expected Behavior

There should be no request timeout.

### To Reproduce

* Go to [YouTube Video Downloader](http://eazyloader.herokuapp.com/yt-downloader/video)
* Enter any lengthy video URL
* Select the 1080p resolution 
* Click on Download
* Wait for 30 seconds and see error

### Anything else?

This is a backend related task

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThisIsBBBGithubAc** [comment]
Hey @ashutoshkrris , you can assign me this issue.....I've solved it......everything working working file .........but one minor problem I'm facing >> Thread is not running in heroku due to not knowing how to write Procfile for that.....could u help me in this?

**Comment by ashutoshkrris** [comment]
Go ahead! Assigning it to you.

**Comment by ThisIsBBBGithubAc** [comment]
i tried both in Procfile :
`web: gunicorn --worker-class eventlet -w 1 main:app
web: gunicorn -w 1 --threads 100 main:app`

but still not running the thread in heroku......could u help me in this case?

**Comment by ashutoshkrris** [comment]
I'm looking for some references too.

For now, can you try this: https://www.py4u.net/discuss/180920

**Comment by ThisIsBBBGithubAc** [comment]
In my case , thread should be executed only, when user click on download button .....not in before first request

**Comment by ashutoshkrris** [comment]
I've created a development branch, whenever you push your code, push it to the development branch
I'll deploy the development branch, and we'll be able to make changes and test without hampering the production server

**Comment by ThisIsBBBGithubAc** [comment]
I've fixed this bug today completely .....now where i will have to push it send the link here...and if i send pull request and if get merged then will it be counted today by hacktoberfest community?

**Comment by ashutoshkrris** [comment]
When you are making the Pull request, you will see an option to select the branch. Choose the development branch

And yes, it will be counted towards Hacktoberfest
You make the PR, let's debug it down completely

**Comment by ThisIsBBBGithubAc** [comment]
Okay, Please keep checking github frequently tonight up to 11.59 pm.  I will try to send PR as soon as possible......now assembling all parts.

**Comment by ashutoshkrris** [comment]
Yep sure.
Go ahead!

**Comment by ThisIsBBBGithubAc** [comment]
Hey @ashutoshkrris , please check its working perfectly [https://bbb-task.herokuapp.com/](url) ....now no issue of request time out....but if video size is larger than heroku free storage , only then it will show error.........otherwise it works well 

Your current production fails to load video from youtube....after merging it might show error so you need to fix it first....or if ur new branch is error free the okay!

**Comment by ashutoshkrris** [comment]
Can you find out the bug in the code?
If you find it, create an issue and work on it.

**Comment by ThisIsBBBGithubAc** [comment]
Sure, I'll do it.....but not today.....I'm very tired!....Now I'm testing the previous error free version (which works fine) for the fast time.....and going to send PR......you can deploy this version (which i have now, everything works) for now on production.

**Comment by ashutoshkrris** [comment]
Yeah, great
Looks like the error has gone away

**Comment by ThisIsBBBGithubAc** [comment]
Did you check it? https://bbb-task.herokuapp.com

**Comment by ashutoshkrris** [comment]
Yeahhh!!
Works perfectly!!

**Comment by ThisIsBBBGithubAc** [comment]
![issue](https://user-images.githubusercontent.com/68538977/139590784-33681d11-55ad-4a86-90f6-76057f40fc5f.PNG)

See, you are trying to download large size video than the existing storage size ....that's why it's not working!....

**Comment by ashutoshkrris** [comment]
Yeah
I tried it..
So, we can set a limit of around 200 MBs

**Comment by ThisIsBBBGithubAc** [comment]
Yeah, Sure

**Comment by ThisIsBBBGithubAc** [comment]
And when you are testing in on localhost .....don't forget to set 'https' to 'http' and vice-versa for prod.....in download.html file of youtube

**Comment by ashutoshkrris** [comment]
Alright

**Comment by ThisIsBBBGithubAc** [comment]
Hey , where should do PR : on main or development?

**Comment by ashutoshkrris** [comment]
Main branch

**Comment by ThisIsBBBGithubAc** [comment]
Now showing this....."This branch has conflicts that must be resolved"

**Comment by ashutoshkrris** [comment]
Did you make the PR?
I suppose you did it in your own repo

**Comment by ThisIsBBBGithubAc** [comment]
Omg.....how to do this correctly?

**Comment by ashutoshkrris** [comment]
Go to your repo.
You will find an option to create pull request.
In the next page, make sure you are making the Pull request to my repo

**Comment by ThisIsBBBGithubAc** [comment]
![okay](https://user-images.githubusercontent.com/68538977/139592845-64079074-b448-46f0-a5b6-320fb1207b8e.PNG)

Are u taking about to select like this?

**Comment by ashutoshkrris** [comment]
Yes

**Comment by ThisIsBBBGithubAc** [comment]
Please resolve the conflict

**Comment by ashutoshkrris** [comment]
Yes, I'll do it and merge the PR

**Comment by ThisIsBBBGithubAc** [comment]
Thank you so much brother 👍

**Comment by ThisIsBBBGithubAc** [comment]
In my Hactoberfest profile , it is showing "project not participating". Why?

**Comment by ashutoshkrris** [comment]
Can you show a screenshot?

**Comment by ThisIsBBBGithubAc** [comment]
![hac](https://user-images.githubusercontent.com/68538977/139594046-0f0e9279-73fb-47a9-be60-90f5863e5b56.PNG)

**Comment by ashutoshkrris** [comment]
Haha
That's not my Repository
That's yours.. it's showing there bcz you made a PR on your repo too

**Comment by ThisIsBBBGithubAc** [comment]
Ohh..i didn't notice the username...how silly i am!

**Comment by ThisIsBBBGithubAc** [comment]
Will u merge it by today?

**Comment by ashutoshkrris** [comment]
I'll merge it today
That won't affect your Hacktoberfest Contribution anyway..
It will still be valid

**Comment by ashutoshkrris** [comment]
@ThisIsBBBGithubAc there's a bug
The bug for which I had to use ffmpeg

If we download a 1080p video, there's no audio.
That's why we need to download audio and video separately and merge them using ffmpeg

**Comment by ThisIsBBBGithubAc** [comment]
Yeah, i forgot to mention this....i commented these part of codes for
temporary reason(to speed up the development, since i didn't have the
ffmpeg file to deploy)...but forgot to uncomment later......you please
uncomment it and deploy it with ffmpeg

**Comment by ashutoshkrris** [comment]
Ahh, okay!
I'll do it

**Comment by ThisIsBBBGithubAc** [comment]
Thank you

**Comment by ThisIsBBBGithubAc** [comment]
Hey @ashutoshkrris , what's this coming again and again in my email......could you please help me in stopping this?
![Screenshot 2021-11-15 114937](https://user-images.githubusercontent.com/68538977/141733941-dc540fe8-30e6-47bf-95bf-f37d22847cdd.png)

**Comment by ashutoshkrris** [comment]
This is due to the slash-assign bot action.
You can delete the .github directory

**Comment by ashutoshkrris** [comment]
Hey @ThisIsBBBGithubAc 
Pinging you for a help
I have created a Slideshare downloader.
The problem is related to websockets.
Please check the slideshare branch

**Comment by ThisIsBBBGithubAc** [comment]
My PC is not working properly since yesterday....i will surely try after my
computer starts working again.

**Comment by ThisIsBBBGithubAc** [comment]
yes, Of course it can ...we just need to launch another thread.
