### ISSUE TITLE
[feature request]: Instagram Videos Downloader

### ISSUE THREAD

**Issue by Anubhab2002** [ashutoshkrris/EazyLoader#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

Instagram Videos Downloader is an upcoming feature to be added to this repository

### Problem/Motivation.

We want to have media like photos and videos for offline access many a times.

### Possible Solution/Pitch.

python's "instalooter" or "instaRadier" modules can be useful

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutoshkrris** [comment]
Sure @Anubhab2002 !
Go ahead with it

**Comment by Anubhab2002** [comment]
Hey @ashutoshkrris, can you tell me why am I getting this particular issue here? I am unable to resolve it.
![Screenshot from 2021-10-06 10-49-25](https://user-images.githubusercontent.com/84004920/136144976-8e9c4788-e0be-4c5b-aa8d-a9fa530d4872.png)

**Comment by ashutoshkrris** [comment]
As mentioned in the [Contributing Guidelines](https://github.com/ashutoshkrris/EazyLoader/blob/main/CONTRIBUTING.md), you need not use `flask run` to run the server.
You can make use of `python main.py` for the same

**Comment by Anubhab2002** [comment]
Hey @ashutoshkrris, an update:
> initially I tried using instaLooter, but its api services are limited to getting content by insta handle or by # of the post
> then I tried to scrap it directly, code ```https://gist.github.com/Anubhab2002/8e024020f35f6b0e856ad0c901f142fb```  but somehow this didn't work(showing response 429 ie, too many requests)
> finally I tried with selenium and chrome webdriver and this thing actually worked find except that there is no widget yet to show that the download is in progress. Also this requires additional things like the webdriver to take control of the website.

That being said, I am trying to refactor it efficiently, in the meantime if you can provide any views or comment regarding this.

**Comment by ashutoshkrris** [comment]
I suppose, we should go with the last choice.

**Comment by whynesspower** [comment]
> @ashutoshkrris , I have completed this issue successfully.
> 
> * used selenium with chrome webdriver to perform the action
> * works in any browser (tested with chrome, firefox and chromium)
> * video and reel both can be downloaded
> * toast message using 'Notify' shows that download is starting
> * error message displayed in case issue is faced in download
> * download folder saved in Downloads folder of the user and is named as `ig-video-<download date>-<download time>.mp4`
> 
> ### issues: none
> * all resolved and working fine on different videos (checked with 3 videos and 1 reel)
> 
> I am placing a Pull Request, please review and merge. ![Screenshot from 2021-10-06 23-16-05](https://user-images.githubusercontent.com/84004920/136260137-d033b6dd-8ce3-4c1d-94ff-28ce700eca14.png) ![Screenshot from 2021-10-06 23-16-19](https://user-images.githubusercontent.com/84004920/136260143-f8b2f42a-6669-45e0-85a3-87d86e03cf63.png)

Great work man!

**Comment by Anubhab2002** [comment]
These are few totally random contents from instagram
