### ISSUE TITLE
[Bug]: IG Downloader part suddenly stops working and starts giving error's (Details Inside)

### ISSUE THREAD

**Issue by NomanBaigA** [ashutoshkrris/EazyLoader#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Error Example -
"Unable to fetch and download the profile picture, try again!"

The same type of error comes with Reels, IGTV, and Stories.

there is one different error that comes with post images.

### Expected Behavior

It should work

### To Reproduce

N/A

### Anything else?

N/A

### Hacktoberfest

- [ ] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashutoshkrris** [comment]
The issue has been resolved, please check now.

**Comment by NomanBaigA** [comment]
> The issue has been resolved, please check now.

Yeah, Thanks :)

**Comment by NomanBaigA** [comment]
I've been attempting to use it for 4 days but it's not working.

**Comment by NomanBaigA** [comment]
after one week it starts working again. maybe the problem is because of instaloader - I asked a question in the discussion related to this problem please reply whenever you see my question.

Thanks ;)
